### ISSUE TITLE
doesn't build due to bad commit in fork of bevy engine

### ISSUE THREAD

**Issue by dylanmc** [insrcd/labyrinth-game#1]
When I tried to build just now, I got a compile error which indicates that a file (`render_resources_node.rs`) in your fork of bevy was checked in with the git merge error flags:

```
   Compiling bevy_render v0.1.3 (https://github.com/insrcd/bevy.git#3362cc44)
error: expected one of `!`, `(`, `+`, `::`, `<`, `>`, or `as`, found keyword `let`
   --> /Users/me/.cargo/git/checkouts/bevy-6fc061e170594249/3362cc4/crates/bevy_render/src/render_graph/nodes/render_resources_node.rs:206:13
    |
204 | <<<<<<< HEAD
    |             - expected one of 7 possible tokens
205 | 
206 |             let total_size = item_size * new_capacity;
    |             ^^^ unexpected token

error: aborting due to previous error

error: could not compile `bevy_render`.
```

**Comment by cyclopunk** [comment]
Hey thanks for reporting this! I'm in the process of moving everything to the bevy 2 release and testing it all out. Should be resolved in a few.

**Comment by insrcd** [comment]
I fixed the merge issue, but due to the changes in 0.2.1, things are pretty broken right now. Going to close this and add some other issues with outstanding problems.  Thanks again for the heads up!

**Comment by dylanmc** [comment]
It's building and running fine now -- looks cute!

**Comment by insrcd** [comment]
Thanks! Still a ton of work to do, but I'm enjoying the challenge ;).
