### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by dlpnet** [insrcd/labyrinth-game#5]
I am trying to build Master (same thing with develop) and get this error:
```❯ cargo run
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C link-arg=-fuse-ld=/usr/local/bin/zld -Zshare-generics=y -Zrun-dsymutil=no --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler
```

if I change to nightly I get other errors also (at the linking step). 
I am on MacOS. (not sure if it matters), using rustc 1.47

**Comment by dlpnet** [comment]
Ok auto replying to myself ... actually you have a specific config in .cargo/config.toml and of course I don't have zld installed.
removing the folder was enough. (I will see to install zld later)

**Comment by insrcd** [comment]
Ya I switched, to the nightly fast compile setup a while ago. Glad you figured it out! ;).

**Comment by insrcd** [comment]
Also I’m only testing on windows so this helps out when I wanna stabilize things for other OSes.
